activity/urls.py
from django.urls import path, re_path
from . import views

app_name = 'activity'

urlpatterns = [
    path('activities', views.activities,name='activities'),
    re_path(r'^view-activity/(?P<pk>.*)/$', views.view_activity,name='view_activity'),
    re_path(r'^create-activity/(?P<pk>.*)/$', views.create_activity,name='create_activity'),
    re_path(r'^delete-activity/(?P<pk>.*)/$', views.delete_activity,name='delete_activity'),
    
    path('activity_questions', views.activity_questions,name='activity_questions'),
    re_path(r'^create_activity_question/(?P<pk>.*)/$', views.create_activity_question,name='create_activity_question'),
]

api/v1/exam/urls.py
from django.urls import path, re_path
from . import views

app_name = 'exam'

urlpatterns = [
    re_path(r'^allotted-exam/$', views.allotted_exam,),
    re_path(r'^questions/$', views.questions,),
    re_path(r'^post-answer/$', views.post_answer,),    
    re_path(r'^previous-question/(?P<pre_question>.*)/$', views.previous_question,),    
    re_path(r'^time-allotted/$', views.time_allotted,),    
    re_path(r'^exam-result/(?P<exam_pk>.*)/$', views.exam_result,),    
]

exam/urls.py
from django.urls import path, re_path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exams', views.exams,name='exams'),
    re_path(r'^view-exam/(?P<pk>.*)/$', views.view_exam,name='view_exam'),
    re_path(r'^create-exam/(?P<pk>.*)/$', views.create_exam, name='create_exam'),  
    re_path(r'^delete-exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),  
    
    path('exams-question', views.exam_questions,name='exam_questions'),
    re_path(r'^create-exam-question/(?P<pk>.*)/$', views.create_exam_question, name='create_exam_question'),  
    re_path(r'^create-exam-question-exam/(?P<exam_pk>.*)/$', views.create_exam_question_without_exam, name='create_exam_question_without_exam'),  
    re_path(r'^update-exam-question-exam/(?P<pk>.*)/$', views.update_exam_question_without_exam, name='update_exam_question_without_exam'),  
    re_path(r'^delete-question/(?P<pk>.*)/$', views.delete_exam_question, name='delete_exam_question'),  
]

mishkath/urls.py
from django import views
from django.conf.urls import include
from django.contrib import admin
from django.views.static import serve
from django.urls import path,re_path

from mishkath import settings


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    
    path('',include(('main.urls'),namespace='main')),
    
    path('app/students/',include(('users.urls'),namespace='users')),
    path('app/learn/',include(('learn.urls'),namespace='learn')),
    path('app/activity/',include(('activity.urls'),namespace='activity')),
    path('app/exams/',include(('exam.urls'),namespace='exam')),
    path('app/payments/',include(('payments.urls'),namespace='payments')),

    re_path('api/v1/auth/',
            include(('api.v1.authentication.urls', 'authentication'), namespace='api_v1_authentication')),
    
    re_path('api/v1/general/',
            include(('api.v1.general.urls', 'general'), namespace='api_v1_general')),
    
    re_path('api/v1/users/',
            include(('api.v1.users.urls', 'users'), namespace='api_v1_users')),
    
    re_path('api/v1/dashboard/',
            include(('api.v1.dashboard.urls', 'dashboard'), namespace='api_v1_dashboard')),
    
    re_path('api/v1/exam/',
            include(('api.v1.exam.urls', 'exam'), namespace='api_v1_exam')),
    
    re_path('api/v1/activity/',
            include(('api.v1.activity.urls', 'activity'), namespace='api_v1_activity')),
    
    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^videos/(?P<path>.*)$', serve, {'document_root': settings.VIDEO_URL}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

exam/forms.py
from django import forms
from django.forms.widgets import TextInput,Select, DateTimeInput,DateInput,CheckboxInput,FileInput

from exam.models import *

class ExamForm(forms.ModelForm):

    class Meta:
        model = Exam
        fields = ['subject','exam_date','exam_type','grade_batch','time_allotted','total_mark','total_questions']

        widgets = {
            'subject': Select(attrs={'class': 'form-control selectpicker'}),
            'exam_date': DateInput(attrs={'class': 'required form-control','id' : 'mdate'}),
            'exam_type': Select(attrs={'class': 'form-control selectpicker'}),
            'grade_batch': Select(attrs={'class': 'form-control selectpicker'}),
            'time_allotted': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Allotted Time'}),
            'total_mark': TextInput(attrs={'type':'number','class': 'required form-control','placeholder' : 'Enter Total mark'}),    
            'total_questions': TextInput(attrs={'type':'number','class': 'required form-control','placeholder' : 'Enter Total Questions'}),    
        }
        
        
class ExamQuestionForm(forms.ModelForm):
    
    class Meta:
        model = Questions
        fields = ['exam','question','question_type','option_a','option_b','option_c','option_d','correct_option','attachment',]

        widgets = {
            'exam': Select(attrs={'class': 'form-control selectpicker'}),
            'question': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Question'}),
            'question_type': Select(attrs={'class': 'form-control selectpicker'}),
            'option_a': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 1'}),
            'option_b': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 2'}),
            'option_c': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 3'}),
            'option_d': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 4'}),
            'correct_option': Select(attrs={'class': 'form-control selectpicker'}),
            'attachment' : FileInput()
        }
        
class ExamQuestionWithoutExamForm(forms.ModelForm):
    
    class Meta:
        model = Questions
        fields = ['question','question_type','option_a','option_b','option_c','option_d','correct_option','attachment',]

        widgets = {
            'question': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Question'}),
            'question_type': Select(attrs={'class': 'form-control selectpicker'}),
            'option_a': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 1'}),
            'option_b': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 2'}),
            'option_c': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 3'}),
            'option_d': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Option 4'}),
            'correct_option': Select(attrs={'class': 'form-control selectpicker'}),
            'attachment' : FileInput()
        }

api/v1/exam/views.py
from datetime import date
from api.v1.dashboard.functions import get_student_batch
from api.v1.exam.serializers import *
from exam.models import Exam
from main.functions import get_auto_id
from rest_framework import status
from rest_framework.decorators import api_view, renderer_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def allotted_exam(request):
    
    exam_type = request.GET.get('exam_type')
    batch = get_student_batch(request)
       
    instances = Exam.objects.filter(grade_batch__batch__pk=batch,exam_type=exam_type,is_deleted=False)

    serialized = ExamSerializers(instances, many=True, context={"request":request})

    response_data = {
        "StatusCode" : 6000,
        "data" : serialized.data,
    }
    return Response(response_data, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def time_allotted(request):
    exam_pk = request.GET.get('exam_pk')
       
    instances = Exam.objects.get(pk=exam_pk,is_deleted=False)

    serialized = QuestionTimeSerializers(instances,context={"request":request})

    response_data = {
        "StatusCode" : 6000,
        "data" : serialized.data,
    }
    return Response(response_data, status=status.HTTP_200_OK)
    

@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def questions(request):
    today = date.today()
    profile = Profile.objects.get(user=request.user)
    pk = request.GET.get('exam_pk')
    try:
        pre_question = request.GET.get('pre_question')
    except:
        pre_question = ''
    
    if Exam.objects.filter(pk=pk,is_deleted=False).exists():
        exam_instance = Exam.objects.get(pk=pk,is_deleted=False)
        student_enrolled_exams = StudentEnrolledExam.objects.values_list('question__pk',flat=True)
        
        instance = Questions.objects.filter(exam__pk=pk,is_deleted=False).exclude(pk__in=student_enrolled_exams).first()
        total_questions = Questions.objects.filter(exam__pk=pk,is_deleted=False).count()
        completed_questions = StudentEnrolledExam.objects.filter(student=profile.pk,student_exam__pk=pk,is_deleted=False).count()
        if not total_questions == completed_questions :
            current_question = completed_questions + 1
        else:
            current_question = completed_questions
            
        if exam_instance.exam_date == today:
            if Questions.objects.filter(exam__pk=pk,is_deleted=False).exists():
                if not total_questions == completed_questions: 
                    
                    if instance.question_type == "objective":
                        serialized = QuestionObjectiveSerializers(instance, context={"request":request})
                        
                        response_data = {
                            "StatusCode" : 6000,
                            "data" : serialized.data,
                            "completed_questions" : completed_questions,
                            "current_question" : current_question,
                            "total_questions" : total_questions,
                            "previous_question_pk" : pre_question,
                            }
                        
                    elif instance.question_type == "attachment":
                        serialized = QuestionNoneObjectiveSerializers(instance, context={"request":request})
                        
                        response_data = {
                            "StatusCode" : 6000,
                            "data" : serialized.data,
                            "completed_questions" : completed_questions,
                            "Total_questions" : total_questions,
                            "previous_question_pk" : pre_question,
                            }
                    
                    elif instance.question_type == "descriptive":
                        serialized = QuestionNoneObjectiveSerializers(instance, context={"request":request})
                        
                        response_data = {
                            "StatusCode" : 6000,
                            "data" : serialized.data,
                            "completed_questions" : completed_questions,
                            "Total_questions" : total_questions,
                            "previous_question_pk" : pre_question,
                            }
                    
                    elif instance.question_type == "descriptive_or_file":
                        serialized = QuestionNoneObjectiveSerializers(instance, context={"request":request})
                        
                        response_data = {
                            "StatusCode" : 6000,
                            "data" : serialized.data,
                            "completed_questions" : completed_questions,
                            "Total_questions" : total_questions,
                            "previous_question_pk" : pre_question,
                            }
                        
                    else:
                        response_data = {
                            "StatusCode" : 6001,
                            # "data" : serialized.data,
                            'message' : 'question type issue'
                            }
                        
                else:
                    response_data = {
                        "StatusCode" : 6001,
                        "message" : "exam completed result will publish soon" 
                        }
            else:
                response_data = {
                    "StatusCode" : 6001,
                    "message" : "no questions" 
                    }
        elif exam_instance.exam_date <= today:
            
            response_data = {
                "StatusCode" : 6001,
                "message" : f'exam completed on {exam_instance.exam_date}'
                }
        elif exam_instance.exam_date >= today:
        
            response_data = {
                "StatusCode" : 6001,
                "message" : f'exam scheduled on {exam_instance.exam_date}'
                }
        else:
            
            response_data = {
                "StatusCode" : 6001,
                "message" : "exam date not scheduled"
                }
    else:
            
        response_data = {
            "StatusCode" : 6001,
            "message" : "exam not scheduled"
            }
        
    return Response(response_data, status=status.HTTP_200_OK)
    
    
    
@api_view(['POST'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def post_answer(request):
    response_data = {}
    c_question_id = request.data['c_question_id']
    
    if Questions.objects.filter(pk=c_question_id,is_deleted=False).exists():
        c_question_instance = Questions.objects.get(pk=c_question_id)
        c_question_type = c_question_instance.question_type
        profile = Profile.objects.get(user=request.user)    
        
        if not StudentEnrolledExam.objects.filter(student__user=request.user,question__pk=c_question_id):
            if c_question_type == "objective" :
                selected_option = request.data['selected_option']
                # auto_id = get_auto_id(StudentEnrolledExam)
                            
                StudentEnrolledExam.objects.create(
                    auto_id=get_auto_id(StudentEnrolledExam),
                    creator=request.user,
                    updater=request.user,
                    student=profile,
                    student_exam=c_question_instance.exam,
                    question=c_question_instance,
                    selected_option=selected_option,
                    )    
                
                response_data = {
                    "StatusCode" : 6000,
                    "message" : "objective question successfully completed",
                    "c_question_pk" : c_question_id,
                    }
                
            elif c_question_type == "attachment":
                attachment = request.data['attachment']
                auto_id = get_auto_id(StudentEnrolledExam)
                
                StudentEnrolledExam.objects.create(
                    auto_id=auto_id,
                    creator=request.user,
                    updater=request.user,
                    student=profile,
                    student_exam=c_question_instance.exam,
                    question=c_question_instance,
                    attachment=attachment,
                    )        
                
                response_data = {
                    "StatusCode" : 6000,
                    "message" : "attachment question successfully completed"
                    }
                
            elif c_question_type == "descriptive":
                descriptive = request.data['descriptive']
                auto_id = get_auto_id(StudentEnrolledExam)
                
                StudentEnrolledExam.objects.create(
                    auto_id=auto_id,
                    creator=request.user,
                    updater=request.user,
                    student=profile,
                    student_exam=c_question_instance.exam,
                    question=c_question_instance,
                    descriptive_answer=descriptive,
                    )
                
                response_data = {
                    "StatusCode" : 6000,
                    "message" : "descriptive question successfully completed"
                    }
                
            elif c_question_type == "descriptive_or_file":
                try:
                    descriptive = request.data['descriptive']            
                except :

templates/exam/exams.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Exams</h4>
   
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            {% comment %} <div class="button-items text-right">
                                <a href="#"><button type="button" class="btn btn-pink btn-icon-square-sm"><i class="fas fa-plus"></i></button></a>
                            </div> {% endcomment %}
                            
                            <form action="{% url 'exam:exams' %}" class="ahs-input" style="text-align:right;" method="get">
                                <div class="row">
                                    {% comment %} <div class="col-lg-9">
                                    </div> {% endcomment %}
                                    <div class="col">
                                        <select name=q class="form-control selectpicker">
                                            <option value="">select exam type</option>
                                            <option value="quarterly">Quarterly</option>
                                            <option value="half_yearly">Half Yearly</option>
                                            <option value="annual">Annual</option>
                                        </select>
                                    </div>
                                    <div class="col-auto align-self-center">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light" style="padding:5px 20px;">Submit</button>
                                    </div>
                                </div>
                            </form>
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Subject</th>
                                            <th>Exam Type</th>
                                            <th>Exam Date</th>
                                            <th>Grade Batch</th>
                                            <th>Time Allotted</th>
                                            <th>Total Mark</th>
                                            <th>Total Questions</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.subject.name}}</td>                                            
                                            <td>{{instance.exam_type}}</td>
                                            <td>{{instance.exam_date}}</td>
                                            <td>{{instance.grade_batch}}</td>
                                            <td>{{instance.time_allotted}}</td>
                                            <td>{{instance.total_mark}}</td>
                                            <td>{{instance.total_questions}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'exam:view_exam' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'exam:create_exam' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                {% comment %} <a href="{% url 'exam:delete_exam' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a> {% endcomment %}
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'exam:delete_exam' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        

templates/exam/view_exam.html
{% extends 'base.html' %}
{% load static %}
{% load exam_templates_tags %}


{% block content %}
<div class="page-content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">Lesson</h4>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Mishkath</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Exam</a></li>
                                {% comment %} <li class="breadcrumb-item active">{{_instances.title}}</li> {% endcomment %}
                            </ol>
                        </div><!--end col-->
                        <div class="col-auto align-self-center">
                            <a href="pages-profile.html#" class="btn btn-sm btn-outline-primary" id="Dash_Date">
                                <span class="day-name" id="Day_Name">Today:</span>&nbsp;
                                <span class="" id="Select_date">Jan 11</span>
                                <i data-feather="calendar" class="align-self-center icon-xs ml-1"></i>
                            </a>
                        </div><!--end col-->  
                    </div><!--end row-->                                                              
                </div><!--end page-title-box-->
            </div><!--end col-->
        </div><!--end row-->
        <!-- end page title end breadcrumb -->

<!--profile card start-->
        <div class="row">
            <div class="col-12">
                <div class="card">
                                                
                    <div class="card-body">
                        <div class="dastone-profile">
                            <div class="row">
                                <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                    <div class="dastone-profile-main">
                                       
                                        <div class="dastone-profile_user-detail">
                                        <h6 class="dastone-user-name">Subject :&nbsp;&nbsp;{{exam_instances.subject.name}}</h6>                                                        
                                            {% comment %} <p class="mb-0 dastone-user-name-post">{{exam_instances.subject.name}}</p>                                                        {% endcomment %}
                                        </div>
                                    </div>                                                
                                </div><!--end col-->


                            </div><!--end row-->
                        </div><!--end f_profile-->                                                                                
                    </div><!--end card-body-->          
                </div> <!--end card-->    
            </div><!--end col-->
        </div><!--end row-->

        <div class="row">

            <div class="col-lg-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-sm-8">                      
                                <h4 class="card-title">Questions</h4>                      
                            </div><!--end col-->
                            <div class="col-sm-4">                      
                                <a class="nav-link p-0" href="{% url 'exam:create_exam_question_without_exam' exam_pk=exam_instances.pk %}" style="text-align:right;">
                                    <button type="button" class="btn btn-outline-primary waves-effect waves-light" style="padding:1px 2px;">Create Question</button> 
                                </a>                 
                            </div><!--end col-->
                        </div>  <!--end row-->                                  
                    </div><!--end card-header-->
                    <div class="card-body" style="max-height:400px;overflow-y: auto;">
                        <ul class="list-group custom-list-group">

                            {% get_questions_in_exam exam_instances.pk  as questions %}
                            {% for question in questions %}                            
                            <li class="list-group-item align-items-center d-flex justify-content-between">
                                <div class="media">
                                    <div class="media-body align-self-center"> 
                                        <h6 class="m-0"><span style="color:blue;">#{{forloop.counter}}&nbsp;&nbsp;</span>{{question.question}}</h6>
                                        {% comment %} <p class="font-10 text-primary">Lesson : {{topic.lesson.name}}</p> {% endcomment %}
                                    </div>
                                </div>
                                <div class="align-self-center">
                                    {% comment %} <a href="{% url 'activity:view_activity' pk=activity.pk %}?redirect_to=activity_view"><i class="las la-pen text-info font-18"></i></a> {% endcomment %}
                                    <a href="{% url 'exam:update_exam_question_without_exam' pk=question.pk %}?redirect_to=view_exam"><i class="las la-pen text-info font-18"></i></a>
                                    <a href="{% url 'exam:delete_exam_question' pk=question.pk %}?redirect_to=view_exam"><i class="las la-trash-alt text-danger font-18"></i></a>
                                </div>

                            </li>
                            {%endfor%}
                            
                        </ul>                                    
                    </div><!--end card-body-->
                </div><!--end card--> 
            </div> <!--end col-->


            <div class="col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-sm-8">                      
                                <h4 class="card-title">Attended Students</h4>                      
                            </div><!--end col-->
                        </div>  <!--end row-->                                  
                    </div><!--end card-header-->
                    
                    <div class="card-body" style="max-height:400px;overflow-y: auto;">
                        <ul class="list-group custom-list-group">

                            {% get_entrolled_exams exam_instances.pk  as students %}
                            {% for student in students %}
                            <li class="list-group-item align-items-center d-flex justify-content-between">
                                <div class="media">
                                    {% comment %} <img src="{{activity.student_id.image.url}}static/assets/images/users/user-1.jpg" height="40" class="mr-3 align-self-center rounded" alt="..."> {% endcomment %}
                                    <img src="{% static 'assets/images/users/user-1.jpg' %}" height="40" class="mr-3 align-self-center rounded" alt="...">
                                    <div class="media-body align-self-center"> 
                                        <h6 class="m-0">{{student.student.name}}</h6>
                                        <p class="font-10 text-primary" style="margin:0;">Score : {{student.lesson.name}}</p>
                                    </div>
                                </div>
                            </li>
                            {%endfor%}
                            
                        </ul>                                    
                    </div><!--end card-body--> 
                </div><!--end card--> 
            </div> <!--end col-->

        </div><!--row closed-->

        

    </div>
</div>

{% endblock content %}