exam/urls.py
from django.urls import path, re_path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exams', views.exams,name='exams'),
    re_path(r'^view-exam/(?P<pk>.*)/$', views.view_exam,name='view_exam'),
    re_path(r'^create-exam/(?P<pk>.*)/$', views.create_exam, name='create_exam'),  
    re_path(r'^delete-exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),  
    
    path('exams-question', views.exam_questions,name='exam_questions'),
    re_path(r'^create-exam-question/(?P<pk>.*)/$', views.create_exam_question, name='create_exam_question'),  
    re_path(r'^create-exam-question-exam/(?P<exam_pk>.*)/$', views.create_exam_question_without_exam, name='create_exam_question_without_exam'),  
    re_path(r'^update-exam-question-exam/(?P<pk>.*)/$', views.update_exam_question_without_exam, name='update_exam_question_without_exam'),  
    re_path(r'^delete-question/(?P<pk>.*)/$', views.delete_exam_question, name='delete_exam_question'),  
]

mishkath/urls.py
from django import views
from django.conf.urls import include
from django.contrib import admin
from django.views.static import serve
from django.urls import path,re_path

from mishkath import settings


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    
    path('',include(('main.urls'),namespace='main')),
    
    path('app/students/',include(('users.urls'),namespace='users')),
    path('app/learn/',include(('learn.urls'),namespace='learn')),
    path('app/activity/',include(('activity.urls'),namespace='activity')),
    path('app/exams/',include(('exam.urls'),namespace='exam')),
    path('app/payments/',include(('payments.urls'),namespace='payments')),

    re_path('api/v1/auth/',
            include(('api.v1.authentication.urls', 'authentication'), namespace='api_v1_authentication')),
    
    re_path('api/v1/general/',
            include(('api.v1.general.urls', 'general'), namespace='api_v1_general')),
    
    re_path('api/v1/users/',
            include(('api.v1.users.urls', 'users'), namespace='api_v1_users')),
    
    re_path('api/v1/dashboard/',
            include(('api.v1.dashboard.urls', 'dashboard'), namespace='api_v1_dashboard')),
    
    re_path('api/v1/exam/',
            include(('api.v1.exam.urls', 'exam'), namespace='api_v1_exam')),
    
    re_path('api/v1/activity/',
            include(('api.v1.activity.urls', 'activity'), namespace='api_v1_activity')),
    
    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^videos/(?P<path>.*)$', serve, {'document_root': settings.VIDEO_URL}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.students,name='students'),
    re_path(r'^create-interview-schedule/(?P<pk>.*)/$', views.create_interview_schedule,name='create_interview_schedule'),
    re_path(r'^subscription-update/(?P<pk>.*)/$', views.subscription_update,name='subscription_update'),
    re_path(r'^assign-batch/(?P<pk>.*)/$', views.assign_batch,name='assign_batch'),
    re_path(r'^view-profile/(?P<pk>.*)/$', views.view_profile,name='view_profile'),
    re_path(r'^edit-profile/(?P<pk>.*)/$', views.edit_profile,name='edit_profile'),
    re_path(r'^delete-profile/(?P<pk>.*)/$', views.delete_profile,name='delete_profile'),
    
        
]

templates/students/student_profile.html
{% extends 'base.html' %}
{% load static %}
{% load users_templates_tags %}


{% block content %}
<div class="page-content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">Profile</h4>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Dastone</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>
                                <li class="breadcrumb-item active">Profile</li>
                            </ol>
                        </div><!--end col-->
                        <div class="col-auto align-self-center">
                            <a href="pages-profile.html#" class="btn btn-sm btn-outline-primary" id="Dash_Date">
                                <span class="day-name" id="Day_Name">Today:</span>&nbsp;
                                <span class="" id="Select_date">Jan 11</span>
                                <i data-feather="calendar" class="align-self-center icon-xs ml-1"></i>
                            </a>
                        </div><!--end col-->  
                    </div><!--end row-->                                                              
                </div><!--end page-title-box-->
            </div><!--end col-->
        </div><!--end row-->
        <!-- end page title end breadcrumb -->

<!--profile card start-->
        <div class="row">
            <div class="col-12">
                <div class="card">
                                                
                    <div class="card-body">
                        <div class="dastone-profile">
                            <div class="row">
                                <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                    <div class="dastone-profile-main">
                                        <div class="dastone-profile-main-pic">
                                            {%if profile_instance.gender == 'male'%}
                                            <img src="{% static 'assets/images/users/user-5.jpg' %}" alt="" height="110" class="rounded-circle">
                                            {%elif profile_instance.gender == 'female'%}
                                            <img src="{% static 'assets/images/users/user-4.jpg' %}" alt="" height="110" class="rounded-circle">
                                            {%endif%}
                                            <span class="dastone-profile_main-pic-change">
                                                <i class="fas fa-camera"></i>
                                            </span>
                                        </div>
                                        <div class="dastone-profile_user-detail">
                                            <h5 class="dastone-user-name">{{profile_instance.name}}</h5>                                                        
                                            <p class="mb-0 dastone-user-name-post">{{profile_instance.grade_batch.grade}}<sup>th</sup> Grade</p>                                                        
                                            <p class="mb-0 dastone-user-name-post">{{profile_instance.grade_batch.batch.title}}</p>                                                        
                                        </div>
                                    </div>                                                
                                </div><!--end col-->
                                
                                <div class="col-lg-4 ml-auto align-self-center">
                                    <ul class="list-unstyled personal-detail mb-0">
                                        <li class=""><i class="las la-phone mr-2 text-secondary font-22 align-middle"></i> <b> phone </b> : {{profile_instance.phone}}</li>
                                        <li class="mt-2"><i class="las la-envelope text-secondary font-22 align-middle mr-2"></i> <b> Email </b> : {{profile_instance.email}}</li>
                                        <li class="mt-2"><i class="dripicons-calendar text-secondary font-22 align-middle mr-2"></i> <b> DOB </b> : {{profile_instance.dob}}</li>
                                        </li>                                                   
                                    </ul>
                                </div><!--end col-->
                                <div class="col-lg-4 ml-auto align-self-center">
                                </div><!--end col-->
                                

                            </div><!--end row-->
                        </div><!--end f_profile-->                                                                                
                    </div><!--end card-body-->          
                </div> <!--end card-->    
            </div><!--end col-->
        </div><!--end row-->
        <!--profile card end-->

        <div class="row">
            <div class="col-lg-4">
                <div class="card"> 
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">                      
                                <h4 class="card-title">Subject Details</h4>                      
                            </div><!--end col-->                                        
                        </div>  <!--end row-->                                  
                    </div><!--end card-header-->
                    <div class="card-body" style="max-height:400px;overflow-y: auto;">

                        {% for topic_details in student_topic_instance %}
                        <div class="border-bottom-dashed mb-4">
                            <div class="media mb-3">
                                {%if topic_details.topic.image%}
                                    <img src="{{topic_details.topic.image.url}}" height="40" class="mr-3 align-self-center rounded" alt="...">
                                {%endif%}
                                <div class="media-body align-self-center"> 
                                    <h6 class="mt-0 mb-1">{{topic_details.topic.lesson.subject.name}}</h6>
                                    {% get_topic_percentage profile_instance.pk topic_details.topic.lesson.subject.pk  as topic_percentage %}
                                    {% comment %} <p class="text-muted mb-1"><span class="text-success">+4.8%</span> From Yesterday</p> {% endcomment %}
                                    <small class="float-right text-muted ml-3 font-11">{{topic_percentage}}%</small>
                                    <div class="progress mt-2" style="height:4px;">
                                        <div class="progress-bar bg-warning-50" role="progressbar" style="width: {{topic_percentage}}%; border-radius:5px;" aria-valuenow="42" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>                                                                                          
                                </div><!--end media body-->
                            </div>                                        
                        </div> 
                        {%endfor%}
                    </div><!--end card-body--> 
                </div><!--end card-->   
            </div><!-- end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Overall performance</h4>
                    </div><!--end card-header-->
                    <div class="card-body">
                        <div class="chart-demo m-0">
                            <div id="apex_radialbar3" class="apex-charts"></div>
                        </div>                                        
                    </div><!--end card-body-->
                </div><!--end card-->
            </div><!--end col-->


        </div>




    </div>
</div>

{% endblock content %}

templates/students/students.html
{% extends 'base.html' %}
{% load static %}
{% load users_templates_tags %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Students</h4>
   
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            {% comment %} <div class="button-items text-right">
                                <a href="#"><button type="button" class="btn btn-pink btn-icon-square-sm"><i class="fas fa-plus"></i></button></a>
                            </div> {% endcomment %}
                            
                            <form action="{% url 'users:students' %}" class="ahs-input" style="text-align:right;" method="get">
                                <div class="row">
                                    {% comment %} <div class="col-lg-9">
                                    </div> {% endcomment %}
                                    <div class="col">
                                        <select name=q class="form-control selectpicker">
                                            <option value="allotted">interview scheduled</option>
                                            <option value="passed">interview completed</option>
                                            <option value="pending">interview failed</option>
                                        </select>
                                    </div>
                                    <div class="col-auto align-self-center">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light" style="padding:5px 20px;">Submit</button>
                                    </div>
                                </div>
                            </form>
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Name</th>
                                            <th>Batch</th>
                                            <th>Grade</th>
                                            <th>Interview Status</th>
                                            <th>Subscription Status</th>
                                            <th>Assign Batch</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.name}}</td>                                            
                                            <td>{{instance.grade_batch.batch.title}}</td>
                                            <td>{{instance.grade_batch.grade.name}}</td>

                                            <td>
                                                {% get_interview_status instance.pk  as interview_status %}
                                                {% if interview_status == "passed" %}
                                                <span class="badge badge-soft-success" style="padding:7px 29px;pointer-events: none;">Passed</span>
                                                {% elif interview_status == "pending" %}
                                                <a href="{% url 'users:create_interview_schedule' pk=instance.pk %}"><button type="button" class="btn btn-outline-info waves-light" style="padding:1px 22px;"></i>Schedule</button>
                                                {% elif interview_status == "allotted" %}
                                                <a href="{% url 'users:create_interview_schedule' pk=instance.pk %}"><button type="button" class="btn btn-outline-warning waves-light" style="padding:1px 8px;"></i>Update Status</button></a>
                                                {% endif %}
                                            </td>

                                            <td>
                                                {% get_subscription_status instance.pk  as subscription_status %}
                                                {% if subscription_status == "not_subscribed" %}
                                                    <button type="button" class="btn btn-primary btn-square btn-outline-dashed waves-effect waves-light" style="padding:1px 10px; pointer-events: none;">Not Subscribed</button>
                                                {% elif subscription_status %}
                                                    <button type="button" class="btn btn-primary waves-effect waves-light" style="padding:1px 10px; pointer-events: none;">Subscribed</button>
                                                {% else %}
                                                    <button type="button" class="btn btn-primary btn-square btn-outline-dashed waves-effect waves-light" style="padding:1px 10px; pointer-events: none;">Subscription Ended</button>
                                                {% endif %}

                                            </td>

                                            <td>
                                                {% get_batch instance.pk  as batch %}
                                                {% if batch %}
                                                <button type="button" class="btn btn-primary waves-effect waves-light" style="padding:1px 10px; pointer-events: none;">Assigned</button>
                                                {% else %}
                                                <a href="{% url 'users:assign_batch' pk=instance.pk %}"><button type="button" class="btn btn-primary btn-square btn-outline-dashed waves-effect waves-light" style="padding:1px 10px; pointer-events: none;">Assign Batch</button></a>
                                                {% endif %}

                                            </td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'users:view_profile' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'users:edit_profile' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a href="{% url 'users:delete_profile' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        