activity/urls.py
from django.urls import path, re_path
from . import views

app_name = 'activity'

urlpatterns = [
    path('activities', views.activities,name='activities'),
    re_path(r'^view-activity/(?P<pk>.*)/$', views.view_activity,name='view_activity'),
    re_path(r'^create-activity/(?P<pk>.*)/$', views.create_activity,name='create_activity'),
    re_path(r'^delete-activity/(?P<pk>.*)/$', views.delete_activity,name='delete_activity'),
    
    path('activity_questions', views.activity_questions,name='activity_questions'),
    re_path(r'^create_activity_question/(?P<pk>.*)/$', views.create_activity_question,name='create_activity_question'),
]

exam/urls.py
from django.urls import path, re_path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exams', views.exams,name='exams'),
    re_path(r'^view-exam/(?P<pk>.*)/$', views.view_exam,name='view_exam'),
    re_path(r'^create-exam/(?P<pk>.*)/$', views.create_exam, name='create_exam'),  
    re_path(r'^delete-exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),  
    
    path('exams-question', views.exam_questions,name='exam_questions'),
    re_path(r'^create-exam-question/(?P<pk>.*)/$', views.create_exam_question, name='create_exam_question'),  
    re_path(r'^create-exam-question-exam/(?P<exam_pk>.*)/$', views.create_exam_question_without_exam, name='create_exam_question_without_exam'),  
    re_path(r'^update-exam-question-exam/(?P<pk>.*)/$', views.update_exam_question_without_exam, name='update_exam_question_without_exam'),  
    re_path(r'^delete-question/(?P<pk>.*)/$', views.delete_exam_question, name='delete_exam_question'),  
]

learn/urls.py
from django.urls import path, re_path

from . import views

app_name = 'learn'

urlpatterns = [
    re_path(r'^unlocked-topics-autocomplete/$', views.UnlockedTopicsAutocomplete.as_view(),
            name='unlocked_topics_autocomplete'),

    path('batches', views.batches, name='batches'),
    re_path(r'^create-batch/(?P<pk>.*)/$', views.create_batch, name='create_batch'),
    re_path(r'^delete-batch/(?P<pk>.*)/$', views.delete_batch, name='delete_batch'),

    path('grades/', views.grades, name='grades'),
    re_path(r'^create-grade/(?P<pk>.*)/$', views.create_grade, name='create_grade'),
    re_path(r'^delete-grade/(?P<pk>.*)/$', views.delete_grade, name='delete_grade'),

    path('grade_batch/', views.grade_batch, name='grade_batch'),
    re_path(r'^create-grade-batch/$', views.create_grade_batch, name='create_grade_batch'),
    re_path(r'^update-grade-batch/(?P<pk>.*)/$', views.update_grade_batch, name='update_grade_batch'),
    re_path(r'^delete-grade-batch/(?P<pk>.*)/$', views.delete_grade_batch, name='delete_grade_batch'),

    path('country/', views.country, name='country'),
    re_path(r'^create-country/(?P<pk>.*)/$', views.create_country, name='create_country'),
    re_path(r'^delete-country/(?P<pk>.*)/$', views.delete_country, name='delete_country'),

    path('courses/', views.courses, name='courses'),
    re_path(r'^create-courses/(?P<pk>.*)/$', views.create_courses, name='create_courses'),
    re_path(r'^delete-courses/(?P<pk>.*)/$', views.delete_courses, name='delete_courses'),

    path('subjects/', views.subjects, name='subjects'),
    re_path(r'^view-subject/(?P<pk>.*)/$', views.view_subject, name='view_subject'),
    re_path(r'^create-subject/(?P<pk>.*)/$', views.create_subjects, name='create_subject'),
    re_path(r'^delete-subject/(?P<pk>.*)/$', views.delete_subject, name='delete_subject'),

    path('lessons/', views.lessons, name='lessons'),
    re_path(r'^view-lesson/(?P<pk>.*)/$', views.view_lesson, name='view_lesson'),
    re_path(r'^create-lesson/(?P<pk>.*)/$', views.create_lesson, name='create_lesson'),
    re_path(r'^create-lesson-with-subject/(?P<sub_pk>.*)/$', views.create_lesson_with_subject,
            name='create_lesson_with_subject'),
    re_path(r'^edit-lesson/(?P<lesson_pk>.*)/$', views.edit_lesson, name='edit_lesson'),
    re_path(r'^delete-lesson/(?P<lesson_pk>.*)/$', views.delete_lesson, name='delete_lesson'),

    path('topics/', views.topics, name='topics'),
    re_path(r'^create-topic-with-lesson/(?P<lesson_pk>.*)/$', views.create_topic_with_lesson,
            name='create_topic_with_lesson'),
    re_path(r'^create-topic/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.create_topic, name='create_topic'),
    re_path(r'^delete-topic/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.delete_topic, name='delete_topic'),
    
    path('up-comming-live-classes/', views.upcomming_live_classes, name='upcomming_live_classes'),
    re_path(r'^create-up-comming-live-classes/(?P<pk>.*)/$', views.create_upcomming_live_classes, name='create_upcomming_live_classes'),    
]

mishkath/urls.py
from django import views
from django.conf.urls import include
from django.contrib import admin
from django.views.static import serve
from django.urls import path,re_path

from mishkath import settings


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    
    path('',include(('main.urls'),namespace='main')),
    
    path('app/students/',include(('users.urls'),namespace='users')),
    path('app/learn/',include(('learn.urls'),namespace='learn')),
    path('app/activity/',include(('activity.urls'),namespace='activity')),
    path('app/exams/',include(('exam.urls'),namespace='exam')),
    path('app/payments/',include(('payments.urls'),namespace='payments')),

    re_path('api/v1/auth/',
            include(('api.v1.authentication.urls', 'authentication'), namespace='api_v1_authentication')),
    
    re_path('api/v1/general/',
            include(('api.v1.general.urls', 'general'), namespace='api_v1_general')),
    
    re_path('api/v1/users/',
            include(('api.v1.users.urls', 'users'), namespace='api_v1_users')),
    
    re_path('api/v1/dashboard/',
            include(('api.v1.dashboard.urls', 'dashboard'), namespace='api_v1_dashboard')),
    
    re_path('api/v1/exam/',
            include(('api.v1.exam.urls', 'exam'), namespace='api_v1_exam')),
    
    re_path('api/v1/activity/',
            include(('api.v1.activity.urls', 'activity'), namespace='api_v1_activity')),
    
    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^videos/(?P<path>.*)$', serve, {'document_root': settings.VIDEO_URL}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

payments/urls.py
from django.urls import path, re_path

from . import views

app_name = 'payments'

urlpatterns = [
    path('subscription-grade', views.subscription_grade, name='subscription_grade'),
    re_path(r'^view-subscription-grade/(?P<pk>.*)/$', views.view_subscription_grade, name='view_subscription_grade'),
    re_path(r'^create-subscription-grade/(?P<pk>.*)/$', views.create_subscription_grade, name='create_subscription_grade'),
    
    re_path(r'^create-subscription-grade-fee/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.create_subscription_grade_fee, name='create_subscription_grade_fee'),
    re_path(r'^delete-subscription-grade-fee/(?P<pk>.*)/$', views.delete_subscription_grade_fee, name='delete_subscription_grade_fee'),
    
    re_path(r'^create-student-subscription/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.create_student_subscription, name='create_student_subscription'),
    
]

users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.students,name='students'),
    re_path(r'^create-interview-schedule/(?P<pk>.*)/$', views.create_interview_schedule,name='create_interview_schedule'),
    re_path(r'^subscription-update/(?P<pk>.*)/$', views.subscription_update,name='subscription_update'),
    re_path(r'^assign-batch/(?P<pk>.*)/$', views.assign_batch,name='assign_batch'),
    re_path(r'^view-profile/(?P<pk>.*)/$', views.view_profile,name='view_profile'),
    re_path(r'^edit-profile/(?P<pk>.*)/$', views.edit_profile,name='edit_profile'),
    re_path(r'^delete-profile/(?P<pk>.*)/$', views.delete_profile,name='delete_profile'),
    
        
]

templates/includes/sidebar/super_admin_side_bar.html
{% load static %}
<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a href="index.html" class="logo">
            <span>
                <img src="{% static 'assets/images/logo.png' %}" alt="logo-small" class="logo-sm">
            </span>
            <span>
                <img src="{% static 'assets/images/logo.png' %}" alt="logo-large" class="logo-lg logo-light">
                <img src="{% static 'assets/images/logo-dark.png' %}" alt="logo-large" class="logo-lg logo-dark">
            </span>
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li class="menu-label mt-0">Main</li>
            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Dashboard</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item"><a class="nav-link" href="index.html"><i class="ti-control-record"></i>Analytics</a></li>
                    <li class="nav-item"><a class="nav-link" href="sales-index.html"><i class="ti-control-record"></i>Sales</a></li> 
                </ul>
            </li>

            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Student Details</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'users:students' %}"><i class="ti-control-record"></i>Students</a>
                        <!-- <a class="nav-link" href="#"><i class="ti-plus"></i></a> -->
                    </li>
                </ul>
            </li>

            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>General</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:batches' %}"><i class="ti-control-record"></i>Batch</a>
                        <a class="nav-link" href="{% url 'learn:create_batch' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:grades' %}"><i class="ti-control-record"></i>Grade</a>
                        <a class="nav-link" href="{% url 'learn:create_grade' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:grade_batch' %}"><i class="ti-control-record"></i>Grade Batch</a>
                        <a class="nav-link" href="{% url 'learn:create_grade_batch'%}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:country' %}"><i class="ti-control-record"></i>Contry</a>
                        <a class="nav-link" href="{% url 'learn:create_country' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:courses' %}"><i class="ti-control-record"></i>Courses</a>
                        <a class="nav-link" href="{% url 'learn:create_courses' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Subjects</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:subjects' %}"><i class="ti-control-record"></i>Subject</a>
                        <a class="nav-link" href="{% url 'learn:create_subject' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:lessons' %}"><i class="ti-control-record"></i>Lesson</a>
                        <a class="nav-link" href="{% url 'learn:create_lesson' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'learn:topics' %}"><i class="ti-control-record"></i>Topic</a>
                        <a class="nav-link" href="{% url 'learn:create_topic' pk='' sub_pk='' %}"><i class="ti-plus"></i></a>
                    </li>
        
                </ul>
            </li>

            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Activities</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'activity:activities' %}"><i class="ti-control-record"></i>Activity</a>
                        <a class="nav-link" href="{% url 'activity:create_activity' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'activity:activity_questions' %}"><i class="ti-control-record"></i>Questions</a>
                        <a class="nav-link" href="{% url 'activity:create_activity_question' pk='' %}"><i class="ti-plus"></i></a>
                    </li>                
                </ul>
            </li>

            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Exams</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'exam:exams' %}"><i class="ti-control-record"></i>Exam</a>
                        <a class="nav-link" href="{% url 'exam:create_exam' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'exam:exam_questions' %}"><i class="ti-control-record"></i>Question</a>
                        <a class="nav-link" href="{% url 'exam:create_exam_question' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

                    <!-- <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="#"><i class="ti-control-record"></i></a>
                        <a class="nav-link" href="#"><i class="ti-plus"></i></a>
                    </li> -->
        
                </ul>
            </li>
            
            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Payment</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'payments:subscription_grade' %}"><i class="ti-control-record"></i>Subscription</a>
                        <a class="nav-link" href="{% url 'payments:create_subscription_grade' pk='' %}"><i class="ti-plus"></i></a>
                    </li>

        
                </ul>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'learn:upcomming_live_classes' %}"><i class="ti-control-record"></i>Live Classes</a>
                <a class="nav-link" href="{% url 'learn:create_upcomming_live_classes' pk='' %}"><i class="ti-plus"></i></a>
            </li>       
        </ul>
    </div>
</div>