exam/urls.py
from django.urls import path, re_path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exams', views.exams,name='exams'),
    re_path(r'^view-exam/(?P<pk>.*)/$', views.view_exam,name='view_exam'),
    re_path(r'^create-exam/(?P<pk>.*)/$', views.create_exam, name='create_exam'),  
    re_path(r'^delete-exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),  
    
    path('exams-question', views.exam_questions,name='exam_questions'),
    re_path(r'^create-exam-question/(?P<pk>.*)/$', views.create_exam_question, name='create_exam_question'),  
    re_path(r'^create-exam-question-exam/(?P<exam_pk>.*)/$', views.create_exam_question_without_exam, name='create_exam_question_without_exam'),  
    re_path(r'^update-exam-question-exam/(?P<pk>.*)/$', views.update_exam_question_without_exam, name='update_exam_question_without_exam'),  
    re_path(r'^delete-question/(?P<pk>.*)/$', views.delete_exam_question, name='delete_exam_question'),  
]

learn/urls.py
from django.urls import path, re_path

from . import views

app_name = 'learn'

urlpatterns = [
    re_path(r'^unlocked-topics-autocomplete/$', views.UnlockedTopicsAutocomplete.as_view(),
            name='unlocked_topics_autocomplete'),

    path('batches', views.batches, name='batches'),
    re_path(r'^create-batch/(?P<pk>.*)/$', views.create_batch, name='create_batch'),
    re_path(r'^delete-batch/(?P<pk>.*)/$', views.delete_batch, name='delete_batch'),

    path('grades/', views.grades, name='grades'),
    re_path(r'^create-grade/(?P<pk>.*)/$', views.create_grade, name='create_grade'),
    re_path(r'^delete-grade/(?P<pk>.*)/$', views.delete_grade, name='delete_grade'),

    path('grade_batch/', views.grade_batch, name='grade_batch'),
    re_path(r'^create-grade-batch/$', views.create_grade_batch, name='create_grade_batch'),
    re_path(r'^update-grade-batch/(?P<pk>.*)/$', views.update_grade_batch, name='update_grade_batch'),
    re_path(r'^delete-grade-batch/(?P<pk>.*)/$', views.delete_grade_batch, name='delete_grade_batch'),

    path('country/', views.country, name='country'),
    re_path(r'^create-country/(?P<pk>.*)/$', views.create_country, name='create_country'),
    re_path(r'^delete-country/(?P<pk>.*)/$', views.delete_country, name='delete_country'),

    path('courses/', views.courses, name='courses'),
    re_path(r'^create-courses/(?P<pk>.*)/$', views.create_courses, name='create_courses'),
    re_path(r'^delete-courses/(?P<pk>.*)/$', views.delete_courses, name='delete_courses'),

    path('subjects/', views.subjects, name='subjects'),
    re_path(r'^view-subject/(?P<pk>.*)/$', views.view_subject, name='view_subject'),
    re_path(r'^create-subject/(?P<pk>.*)/$', views.create_subjects, name='create_subject'),
    re_path(r'^delete-subject/(?P<pk>.*)/$', views.delete_subject, name='delete_subject'),

    path('lessons/', views.lessons, name='lessons'),
    re_path(r'^view-lesson/(?P<pk>.*)/$', views.view_lesson, name='view_lesson'),
    re_path(r'^create-lesson/(?P<pk>.*)/$', views.create_lesson, name='create_lesson'),
    re_path(r'^create-lesson-with-subject/(?P<sub_pk>.*)/$', views.create_lesson_with_subject,
            name='create_lesson_with_subject'),
    re_path(r'^edit-lesson/(?P<lesson_pk>.*)/$', views.edit_lesson, name='edit_lesson'),
    re_path(r'^delete-lesson/(?P<lesson_pk>.*)/$', views.delete_lesson, name='delete_lesson'),

    path('topics/', views.topics, name='topics'),
    re_path(r'^create-topic-with-lesson/(?P<lesson_pk>.*)/$', views.create_topic_with_lesson,
            name='create_topic_with_lesson'),
    re_path(r'^create-topic/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.create_topic, name='create_topic'),
    re_path(r'^delete-topic/(?P<pk>.*)/(?P<sub_pk>.*)/$', views.delete_topic, name='delete_topic'),
    
    path('up-comming-live-classes/', views.upcomming_live_classes, name='upcomming_live_classes'),
    re_path(r'^create-up-comming-live-classes/(?P<pk>.*)/$', views.create_upcomming_live_classes, name='create_upcomming_live_classes'),    
]

mishkath/urls.py
from django import views
from django.conf.urls import include
from django.contrib import admin
from django.views.static import serve
from django.urls import path,re_path

from mishkath import settings


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    
    path('',include(('main.urls'),namespace='main')),
    
    path('app/students/',include(('users.urls'),namespace='users')),
    path('app/learn/',include(('learn.urls'),namespace='learn')),
    path('app/activity/',include(('activity.urls'),namespace='activity')),
    path('app/exams/',include(('exam.urls'),namespace='exam')),
    path('app/payments/',include(('payments.urls'),namespace='payments')),

    re_path('api/v1/auth/',
            include(('api.v1.authentication.urls', 'authentication'), namespace='api_v1_authentication')),
    
    re_path('api/v1/general/',
            include(('api.v1.general.urls', 'general'), namespace='api_v1_general')),
    
    re_path('api/v1/users/',
            include(('api.v1.users.urls', 'users'), namespace='api_v1_users')),
    
    re_path('api/v1/dashboard/',
            include(('api.v1.dashboard.urls', 'dashboard'), namespace='api_v1_dashboard')),
    
    re_path('api/v1/exam/',
            include(('api.v1.exam.urls', 'exam'), namespace='api_v1_exam')),
    
    re_path('api/v1/activity/',
            include(('api.v1.activity.urls', 'activity'), namespace='api_v1_activity')),
    
    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^videos/(?P<path>.*)$', serve, {'document_root': settings.VIDEO_URL}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

learn/views.py
from dal import autocomplete
import datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from learn.forms import BatchesForm, ClassForm, CountryForm, CoursesForm, GradeBatchForm, LessonFormWithSubject, \
    LessonFormWithoutSubject, SubjectsForm, TopicFormWithLesson, TopicFormWithoutLesson, UpCommingLiveClassesForm
from learn.models import Batch, Grade, GradeBatch, Lesson, Subject, Topic, UpCommingLiveClasses
from main.functions import get_auto_id
from main.models import Country, Courses


class UnlockedTopicsAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self, *args, **kwargs):
        items = Topic.objects.filter(is_deleted=False)
        if self.q:
            items = items.filter(Q(name__istartswith=self.q))
        else:
            pass
        return items


@login_required
def batches(request):
    """
    student batches listings, eg:- night batch, morning batch etc
    :param request:
    :return: batch list view
    """
    instances = Batch.objects.filter(is_deleted=False).order_by("-id")

    context = {
        'instances': instances,
        'page_name' : 'Batches'
    }
    return render(request, 'learn/batches.html', context)


@login_required
def create_batch(request, pk):
    """
    create and update operation of batches
    :param request:
    :param pk:
    :return:
    """
    # check pk for getting instance
    if pk:
        instance = get_object_or_404(Batch, pk=pk)
    else:
        instance = ''

    message = ''
    if request.method == 'POST':
        # if instance go to edit
        if instance:
            form = BatchesForm(request.POST, instance=instance)
        else:
            form = BatchesForm(request.POST)
            
        if form.is_valid():
            data = form.save(commit=False)
            if not instance:
                data.auto_id = get_auto_id(Batch)
                data.creator = request.user
            else:
                data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            return redirect(reverse('learn:batches'))

        else:
            message = "Form Validation Error"
            print(message)

    if instance:
        form = BatchesForm(instance=instance)
    else:
        form = BatchesForm()

    context = {
        'form': form,
        'message': message,
        'page_name' : 'Create Batch',
        'is_need_datetime_picker' : True,
    }

    return render(request, 'creates/create.html', context)


@login_required
def delete_batch(request, pk):
    """
    batch deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Batch.objects.filter(pk=pk).update(is_deleted=True)

    return redirect(reverse('learn:batches'))


@login_required
def grades(request):
    instances = Grade.objects.filter(is_deleted=False).order_by("-id")

    context = {
        'instances': instances,
        'page_name' : 'Grades'
    }
    return render(request, 'learn/grade.html', context)


@login_required
def create_grade(request, pk):
    """
    creation of class eg:- 1, 2, +2, etcc
    :param request:
    :param pk:
    :return:
    """
    if pk:
        instance = get_object_or_404(Grade, pk=pk)
    else:
        instance = ''

    message = ''
    if request.method == 'POST':
        if instance:
            form = ClassForm(request.POST, instance=instance,files=request.FILES)
        else:
            form = ClassForm(request.POST,files=request.FILES)

        if form.is_valid():
            data = form.save(commit=False)
            if not instance:
                data.auto_id = get_auto_id(Grade)
                data.creator = request.user
            else:
                data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            return redirect(reverse('learn:grades'))

        else:
            message = "Form Validation Error"

    if instance:
        form = ClassForm(instance=instance)
    else:
        form = ClassForm()

    context = {
        'form': form,
        'message': message,
        'instance': instance,
        'is_need_select2': True,
        'is_need_forms': True,
        'page_name' : 'Create Grade'
    }

    return render(request, 'creates/create.html', context)


@login_required
def delete_grade(request, pk):
    """
    mark grade as deleted
    :param request:
    :param pk:
    :return:
    """
    Grade.objects.filter(pk=pk).update(is_deleted=True)

    return redirect(reverse('learn:grades'))


@login_required
def grade_batch(request):
    """
    combination of grade and batch
    :param request:
    :return:
    """
    instances = GradeBatch.objects.filter(is_deleted=False).order_by("-id")

    context = {
        'instances': instances,
        'page_name' : 'Grade Batch'
    }
    return render(request, 'learn/grade_batch.html', context)


@login_required
def create_grade_batch(request):
    """
    creation of grade batch
    :param request:
    :return:
    """
    message = ''
    
    if request.method == 'POST':

        form = GradeBatchForm(request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            unlocked_topics = request.POST.getlist('unlocked_topic')
            # print("Un locked topics ", unlocked_topics)
            data.auto_id = get_auto_id(GradeBatch)
            data.creator = request.user
            data.updater = request.user
            data.save()

            message = f"The data is {data.pk}"
            instance = GradeBatch.objects.get(pk=data.pk)

            # save many_to_many unlocked topics instance
            for i in unlocked_topics:
                instance.unlocked_topic.add(i)

            instance.save()
            return redirect(reverse('learn:grade_batch'))

        else:
            message = "Form Validation Error"
    else:
        form = GradeBatchForm()

        context = {
            'form': form,
            'message': message,
            "is_need_forms": True,
            'is_need_select2': True,
            'page_name' : 'Create Grade Batch',

        }

    return render(request, 'creates/create.html', context)


@login_required
def update_grade_batch(request, pk):
    """
    edit of grade batch
    :param request:
    :param pk:
    :return:
    """
    message = ""
    instance = get_object_or_404(GradeBatch, pk=pk)
    if request.method == 'POST':
        if instance:
            form = GradeBatchForm(request.POST, instance=instance)
            # instance.unlocked_topic.clear()
            # instance.save()s

        if form.is_valid():
            data = form.save(commit=False)
            unlocked_topics = request.POST.getlist('unlocked_topic')

            if not instance:
                # print("srting.....")
                data.auto_id = get_auto_id(GradeBatch)
                data.creator = request.user
                data.updater = request.user
                data.save()
                temp_instance = get_object_or_404(GradeBatch, pk=data.pk)
                # print("Temp instance===>>",data)

            else:
                data.date_updated = datetime.datetime.today()
                # print("Type of unlocked ==>>", type(unlocked_topics))

                # clear all existing topics and saves to field
                instance.unlocked_topic.clear()
                for i in unlocked_topics:
                    instance.unlocked_topic.add(i)

                instance.save()

                data.updater = request.user
                data.save()
            # print("test data ---------------", data.pk)

            message = "Success"

            return redirect(reverse('learn:grade_batch'))

        else:
            message = "Form Validation Error"

    #     print("Message------------------------------: ", message)
    # print("Message-----------------------------ffgerf43-: ", message)
    form = GradeBatchForm(instance=instance)

    context = {
        'form': form,
        'message': message,
        'instance': instance,
        'page_name' : 'Create Grade Batch'
    }

    return render(request, 'creates/create.html', context)


@login_required
def delete_grade_batch(request, pk):
    GradeBatch.objects.filter(pk=pk).update(is_deleted=True)

    return redirect(reverse('learn:grade_batch'))


@login_required
def country(request):
    instances = Country.objects.filter(is_deleted=False).order_by("-id")

    context = {
        'instances': instances,
        'page_name' : 'Country'
    }
    return render(request, 'general/country.html', context)


@login_required
def create_country(request, pk):
    if pk:
        instance = get_object_or_404(Country, pk=pk)
    else:
        instance = ''

    message = ''
    if request.method == 'POST':
        if instance:
            form = CountryForm(request.POST, instance=instance)
        else:
            form = CountryForm(request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            if not instance:
                data.auto_id = get_auto_id(Country)
                data.creator = request.user
            else:
                data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            return redirect(reverse('learn:country'))

        else:
            message = "Form Validation Error"

    if instance:
        form = CountryForm(instance=instance)
    else:
        form = CountryForm()

    context = {
        'form': form,
        'message': message,
        'instance': instance,
        'page_name' : 'Create Country'
    }

    return render(request, 'creates/create.html', context)


@login_required
def delete_country(request, pk):
    Country.objects.filter(pk=pk).update(is_deleted=True)

templates/learn/grade.html
{% extends 'base.html' %}
{% load static %}
{% load users_templates_tags %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Classes</h4>
   
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        
                        <!--end card-header-->
                        <div class="card-body">
                            {% comment %} <div class="button-items text-right">
                                <a href="#"><button type="button" class="btn btn-pink btn-icon-square-sm"><i class="fas fa-plus"></i></button></a>
                            </div> {% endcomment %}
                            
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>Qualification</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{%if instance.image%}
                                                <img src="{{instance.image.url}}" class="rounded-circle thumb-xs mr-1">
                                            {% endif %}</td>
                                            {% comment %} <td>{{instance.image}}</td>                                             {% endcomment %}
                                            <td>{{instance.name}}</td>
                                            <td>{{instance.description}}</td>
                                            <td>{{instance.qualification}}</td>

                                            <td class="text-right">
                                                {% comment %} <a href="{% url 'learn:view_batch' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a> {% endcomment %}
                                                <a href="{% url 'learn:create_grade' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a href="{% url 'learn:delete_grade' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        

templates/learn/subject_view.html
{% extends 'base.html' %}
{% load static %}
{% load learn_templates_tags %}


{% block content %}
<div class="page-content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">Subject</h4>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Dastone</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>
                                <li class="breadcrumb-item active">Profile</li>
                            </ol>
                        </div><!--end col-->
                        <div class="col-auto align-self-center">
                            <a href="pages-profile.html#" class="btn btn-sm btn-outline-primary" id="Dash_Date">
                                <span class="day-name" id="Day_Name">Today:</span>&nbsp;
                                <span class="" id="Select_date">Jan 11</span>
                                <i data-feather="calendar" class="align-self-center icon-xs ml-1"></i>
                            </a>
                        </div><!--end col-->  
                    </div><!--end row-->                                                              
                </div><!--end page-title-box-->
            </div><!--end col-->
        </div><!--end row-->
        <!-- end page title end breadcrumb -->

<!--profile card start-->
        <div class="row">
            <div class="col-12">
                <div class="card">
                                                
                    <div class="card-body">
                        <div class="dastone-profile">
                            <div class="row">
                                <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                    <div class="dastone-profile-main">
                                        <div class="dastone-profile-main-pic">
                                            {% comment %} <img src="{% static 'assets/images/users/user-4.jpg' %}" alt="" height="110" class="rounded-circle"> {% endcomment %}
                                            {%if subject_instance.image%}
                                                <img src="{{subject_instance.image.url}}" class="img-thumbnail"></td>
                                            {%endif%}
                    
                                        </div>
                                        <div class="dastone-profile_user-detail">
                                            <h6 class="dastone-user-name">{{subject_instance.name}}</h6>                                                        
                                            <p class="mb-0 dastone-user-name-post">{{subject_instance.description}}</p>                                                       
                                        </div>
                                    </div>                                                
                                </div><!--end col-->
                                
                                <div class="col-lg-4 ml-auto align-self-center">
                                    {% get_total_status subject_instance.pk  as status %}
                                    <ul class="list-unstyled personal-detail mb-0">
                                        <li class="mt-2"><b> Total Lesson </b> : {{status.lesson_instances_count}}</li>
                                        <li class="mt-2"><b> Total Topics </b> : {{status.topic_instances_count}}</li>
                                        <li class="mt-2"><b> Last Added Topic </b> : {{status.latest_added_topic}}</li>
                                        </li>                                                   
                                    </ul>
                                </div><!--end col-->
                                <div class="col-lg-4 ml-auto align-self-center">
                                </div><!--end col-->
                                

                            </div><!--end row-->

                            

                        </div><!--end f_profile-->                                                                                
                    </div><!--end card-body-->          
                </div> <!--end card-->    
            </div><!--end col-->
        </div><!--end row-->

        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-sm-8">                      
                                <h4 class="card-title">Lessons</h4>                      
                            </div><!--end col-->
                            <div class="col-sm-4">                      
                                <a class="nav-link p-0" href="{% url 'learn:create_lesson_with_subject' sub_pk=subject_instance.pk %}" style="text-align:right;">
                                    <button type="button" class="btn btn-outline-primary waves-effect waves-light" style="padding:1px 4px;">add lesson</button> 
                                </a>                 
                            </div><!--end col-->
                        </div>  <!--end row-->                                  
                    </div><!--end card-header-->
                    <div class="card-body" style="max-height:400px;overflow-y: auto;">
                        <ul class="list-group custom-list-group">

                            {% get_lessons_in_subject subject_instance.pk  as lessons %}
                            {% for lesson in lessons %}                            
                            <li class="list-group-item align-items-center d-flex justify-content-between">
                                <div class="media">
                                    <img src="{{lesson.image.url}}" height="40" class="mr-2 align-self-center rounded" alt="...">
                                    <div class="media-body align-self-center"> 
                                        <h6 class="m-0">{{lesson.name}}</h6>
                                    </div><!--end media body-->
                                </div>
                                <div class="align-self-center">

                                    <a href="{% url 'learn:create_topic_with_lesson' lesson_pk=lesson.pk %}">
                                    <span class="badge badge-outline-primary" style="font-size:12px !important">create topic</span>
                                    </a>

                                    <a class="dropdown-toggle arrow-none" id="dLabel11" data-toggle="dropdown" href="tables-basic.html#" role="button" aria-haspopup="false" aria-expanded="false">
                                        <i class="las la-ellipsis-v font-16 text-muted"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel11">
                                        <a class="dropdown-item" href="{% url 'learn:view_lesson' pk=lesson.pk %}"><i class="las la-eye text-info font-14"></i>&nbsp;&nbsp;View</a>
                                        <a class="dropdown-item" href="{% url 'learn:edit_lesson' lesson_pk=lesson.pk %}"><i class="las la-pen text-info font-14"></i>&nbsp;&nbsp;Edit</a>
                                        <a class="dropdown-item" href="{% url 'learn:delete_lesson' lesson_pk=lesson.pk %}?redirect_to=subject"><i class="las la-trash-alt text-danger font-14"></i>&nbsp;&nbsp;Delete</a>
                                    </div>
                                    
                                    <div class="apexchart-wrapper w-30 align-self-center">                                                    
                                        <div id="dash_spark_2" class="chart-gutters"></div>
                                    </div>
                                </div>
                            </li>
                            {%endfor%}
                            
                        </ul>                                    
                    </div><!--end card-body--> 
                </div><!--end card--> 
            </div> <!--end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-sm-8">                      
                                <h4 class="card-title">Topics</h4>                      
                            </div><!--end col-->
                            <div class="col-sm-4">                      
                                <a class="nav-link p-0" href="{% url 'learn:topics' %}" style="text-align:right;">
                                    <button type="button" class="btn btn-outline-primary waves-effect waves-light" style="padding:1px 4px;">View all Topics</button> 
                                </a>                 
                            </div><!--end col-->
                        </div>  <!--end row-->                                  
                    </div><!--end card-header-->
                    <div class="card-body" style="max-height:400px;overflow-y: auto;">
                        <ul class="list-group custom-list-group">

                            {% get_topics_in_subject subject_instance.pk  as topics %}
                            {% for topic in topics %}                            
                            <li class="list-group-item align-items-center d-flex justify-content-between">
                                <div class="media">
                                    <img src="{{topic.image.url}}" height="40" class="mr-3 align-self-center rounded" alt="...">
                                    <div class="media-body align-self-center"> 
                                        <h6 class="m-0">{{topic.name}}</h6>
                                        <p class="font-10 text-primary">Lesson : {{topic.lesson.name}}</p>
                                    </div>
                                </div>

                                <div class="align-self-center">
                                    {% comment %} <a href="{% url 'learn:create_topic' pk=topic.pk sub_pk=topic.lesson.subject.pk %}"><i class="las la-eye text-info font-18"></i></a> {% endcomment %}
                                    <a href="{% url 'learn:create_topic' pk=topic.pk sub_pk=topic.lesson.subject.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                    <a href="{% url 'learn:delete_topic' pk=topic.pk sub_pk=topic.lesson.subject.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                </div>

                            </li>
                            {%endfor%}
                            
                        </ul>                                    
                    </div><!--end card-body--> 
                </div><!--end card--> 
            </div> <!--end col-->


        <!--profile card end-->



    </div>
</div>

{% endblock content %}